ncbc = """
Mary Eliza McRae <mountaingirl88@gmail.com>,
Rodney Tillinghast <rodney.tillinghast@gmail.com>,
Brandon Moyer <moyerbs07@gmail.com>,
ncbuning@juno.com,
Chris Cartaino <ccartaino@gmail.com>,
Gary Morgan <garym4991@hotmail.com>,
whit@bondbrothersbeer.com,
Keith Houck <keithahouck@gmail.com>,
Dennis Pike <daspiker@gmail.com>,
Malt Licker <MaltLicker@earthlink.net>,
Daniel Bradford <dfullerbradford@gmail.com>,
Chris Creech <chris@glass-jug.com>,
Clint Eaker <ceaker@mindspring.com>,
Nick Passarella <nickpassarella@gmail.com>,
Jimmy VerVaecke <jvervaecke@nc.rr.com>,
edarnell@raleighchamber.org,
Paul Goodell <paul.m.goodell@gmail.com>,
wenzelt@netzero.net,
Jessica Chaffee <jlchafe@gmail.com>,
derick shular <derickshular@gmail.com>,
Daniel Sherfey <ddsherfey@gmail.com>,
David Byer <byer.david@gmail.com>,
sam victory <Sam_Victory@yahoo.com>,
Kevin Lindley <etcetrah@gmail.com>,
ncbrewer@live.com,
egalamb@yahoo.com,	
bill gerds <terds53@gmail.com>,
Brian Johnson <bjcpg1271@gmail.com>,
Michael McGuire <mmcguire916@gmail.com>,
John Oldendorf <john@cloudsbrewing.com>,
David Overholser <udoverholser@gmail.com>,
John Rankin <john.rankin84@gmail.com>,
john_mth@yahoo.com,
Aaron Strickland <ahstrick@gmail.com>,
Thomas Vincent <geistbear@gmail.com>,
Mike Wallace <ncmike27609@yahoo.com>,
Greg Wolfe <gdwolfe273@gmail.com>,
eric@ericsmith.beer,
Kevin Thorngren <kevin.thorngren@gmail.com>,
Chris Hilgar <hilgar@outlook.com>,
James McNulty <jrm0829@gmail.com>,
Joe & Cindy <4dufresnes@gmail.com>,
Steve Nance <sanance99@yahoo.com>,
federalagentfederal <federalagentfederal@gmail.com>,
Tom <sharkguy05@yahoo.com>,
Robert Fondren <fondren@cox.net>,
Tim Winslett <twinslett@winslettit.com>,
john.hammond@ncagr.gov,
Michelle Reynolds <reynolds.michelle@gmail.com>,
Doug Piper <dougpipersr@gmail.com>,
Manfred Stanfield <msuppan@gmail.com>,
Sarah Ficke <sficke@marymount.edu>,Integration
Jen Blair <Jen@underthejenfluence.beer>,
Camille Torchiano-Tamlyn <millatorch@yahoo.com>,
Bob Larsen <bob.larsen@ymail.com>,
Kevin Tamlyn <ktamlyn@gmail.com>,
Heiko Rath <heikor@gmail.com>,
Jasmine Bamlet <jasminebamlet579@gmail.com>,
jeniferlarsen@hotmail.com,
Amanda Scherle <alscherle@gmail.com>,
Brittany Judy <brittanyjudy1987@gmail.com>,
"Chandler V." <chandler0201@gmail.com>,
Cindy Oatley <coatley42@gmail.com>,
Valerie Renard <vrenard21@gmail.com>,
brh555@alumni.unc.edu,
margot.ripley@gmail.com,
j hopson <hopson@mindspring.com>,
Ellen Hunter <ehunter6969@gmail.com>,
John Jeidy <jcjeidy@hotmail.com>,
dgreen43@frontier.com,
Clark Morris <klarc.morris@gmail.com>,
Doug Hensel <hashingopus@gmail.com>,
Reid Campbell <racampbell.junk@gmail.com>,
Bob Allegretti <ballegre@gmail.com>,
jenny.hahn530@gmail.com,
erik@fullsteam.ag,
tholmes@raleighchamber.org,
Karl Herzberg <karlherzberg@msn.com>,
Hannah Ward <hannaheward@hotmail.com>,
bhenthorn@nc.rr.com,
Richard Cox <kinggoji@gmail.com>,
Erin Lawrimore <elawrimore32@gmail.com>,
Info@raleighbrewscruise.com,
Steven W <stevenmward84@gmail.com>,
Ryan Barnes <rybarnes@gmail.com>,
andrew clement <acleme1709@gmail.com>,
Joe Gizmo Brew Works <joewalton@gizmobrewworks.com>,
catherine pearce <catherinepearce15@gmail.com>,
Fawn Pattison <fawnpea@gmail.com>,
James Walker <Jwalkeriv@hotmail.com>,
Jeremy Stamps <jeremy.d.stamps@gmail.com>,
John Kater <john@huskehardware.com>,
rehyburg@hotmail.com,
Tony@kymudworks.com,
mark stoehr <mstoehr@triad.rr.com>,
Tom Crast <Tom.crast@gmail.com>,
daveg@rivermenbrewingcompany.com,
Cathy McLaughlin <clgdjm@gmail.com>,
Dan McLaughlin <djmclg@gmail.com>,
Jen Blair <jen@underthejenfluence.beer>,
sturner@blueblazebrewing.com,
chris@birdsongbrewing.com,
peter@residentculturebrewing.com,
mcmichael.andrew@gmail.com,
andy.pinz@gmail.com,
beerking1@verizon.net,
beorlufu@gmail.com,
bill_dubas@hotmail.com,
brewboy4u@gmail.com,
Eugeniamobrown@gmail.com,
flhunter@sbcglobal.net,
jazzbam@gmail.com,
Jen.sharp.knott@gmail.com,
jnsmorgan@bellsouth.net,
kknott@vt.edu,
lagerman64@yahoo.com,
mark@heft.haus,
pascoejeff@gmail.com,
samv@wisemanbrewing.com,
shficke@gmail.com,
tonyhamric@yahoo.com,
cat@jordanlakebrewing.com,
dg@lostworldsbeer.com,
dave@ncbeerguys.com,
jmadel72@icloud.com
"""

bjcp = [
    "brianbickel@yahoo.com",
"smurprey@nc.rr.com",
"brian.sico@gmail.com",
"rodney.tillinghast@gmail.com",
"davidmaida7@gmail.com",
"reinkster@hotmail.com",
"joshua.r.austin@gmail.com",
"melissa.a.chaney@gmail.com",
"craftbeerspecialist@gmail.com",
"pgomez@whitelabs.com",
"hickey.brian.p@gmail.com",
"juliejjones@gmail.com",
"hughmmunro@gmail.com",
"joshualrau@gmail.com",
"andysally57@gmail.com",
"kevin.thorngren@gmail.com",
"hawyatt2@gmail.com",
"batdavek@gmail.com",
"stephenstreeter42@gmail.com",
"happyvalleyenv@gmail.com",
"dakidjwm@hotmail.com",
"gregsolsen5@gmail.com",
"jayson.gowdy@gmail.com",
"ncbuning@juno.com",
"ccartaino@gmail.com",
"gjm499@gmail.com",
"paul.wasmund@gmail.com",
"mikerobrew@aol.com",
"whit.baker2@gmail.com",
"crik@mac.com",
"federalagentfederal@gmail.com",
"keithahouck@gmail.com",
"dwpike2000@yahoo.com",
"bbeauchemin@carolina.rr.com",
"jen@underthejenfluence.beer",
"tom.crast@gmail.com",
"xzymurgist@aol.com",
"jdomm23@gmail.com",
"lauren.k.domm@gmail.com",
"pfolse@carolina.rr.com",
"henderson.tom@gmail.com",
"kevmar@computer.org",
"JRM657@gmail.com",
"pnthrsfan@hotmail.com",
"bruphone@gmail.com",
"dr007@windstream.net",
"thom.carpenter@gmail.com",
"beustice@bellsouth.net",
"punkstyle@yahoo.com",
"rtlovelace3@gmail.com",
"bballantine@gmail.com",
"rybarnes@gmail.com",
"daniel@allaboutbeer.com",
"chriscreech10@gmail.com",
"ceaker@mindspring.com",
"sixmmblowback@gmail.com",
"morrison@bigwhoop.org",
"andy.pinz@gmail.com",
"kredmond37@gmail.com",
"dvanollefen@gmail.com",
"Jeremy.D.Stamps@Gmail.com",
"jnsmorgan@bellsouth.net",
"paul.m.goodell@gmail.com",
"lorax429@gmail.com",
"edarne111@gmail.com",
"wenzelt@netzero.net",
"waltbilous@gmail.com",
"miranda_knowles2@yahoo.com",
"williamtbrown1@gmail.com",
"chsyhkr@gmail.com",
"snazzqueen@gmail.com",
"mark@gibbshundred.com",
"derickshular@gmail.com",
"ddsherfey@gmail.com",
"crispy275@gmail.com",
"civesdal@yahoo.com",
"pruchajim@gmail.com",
"fuggles59@gmail.com",
"t3smith33@gmail.com",
"byer.david@gmail.com",
"RLANE17@GMAIL.COM",
"davidjasonrandall@gmail.com",
"ptaylor968@gmail.com",
"hapeterman@gmail.com",
"mike@marblevisions.com",
"jlchafe@gmail.com",
"mstoehr@triad.rr.com",
"tonyhamric@yahoo.com",
"jcmcmath@hotmail.com",
"shaken9@gmail.com",
"jason@homebrewedstaffords.com",
"npcarpenter@yahoo.com",
"richardcameronwiggins@gmail.com",
"hughr@live.com",
"jeff.brungard@twc.com",
"overbyden@yahoo.com",
"sintral@gmail.com",
"milleraaronjay@gmail.com",
"Sam_Victory@yahoo.com",
"etcetrah@gmail.com",
"bill_dubas@hotmail.com",
"egalamb@yahoo.com",
"terds53@gmail.com",
"bjcpg1271@gmail.com",
"kleczewj@yahoo.com",
"mmcguire916@gmail.com",
"mountaingirl88@gmail.com",
"john@cloudsbrewing.com",
"udoverholser@gmail.com",
"williamposke@yahoo.com",
"john.rankin84@gmail.com",
"ahstrick@gmail.com",
"Thomas_Vincent@yahoo.com",
"ncmike27609@yahoo.com",
"jwmongrel@yahoo.com",
"ehwelding@gmail.com",
"jpayne75th@gmail.com",
"corey@balsamfallsbrewing.com",
"michaelpdixon@gmail.com",
"matthew.nanney@aecom.com",
"waltbop22@NC.RR.com",
"brewcnc@yahoo.com",
"SeanCBeer@gmail.com",
"hilgar@outlook.com",
"dsheitter5349@charter.net",
"bernie@thekesselgroup.com",
"jrm0829@yahoo.com",
"joesdufresne@gmail.com",
"jtkoebel@gmail.com",
"sreuschle@gmail.com",
"jtaber01@gmail.com",
"F0497.bjcpemail@gmail.com",
"mentzerbrian@yahoo.com",
"elgin.hawthorne@gmail.com",
"john.h.dugue@gmail.com",
"veronee@email.com",
"stephenjstaples@gmail.com",
"rdbowers@g.cofc.edu",
"joshwheller@gmail.com",
"losulli@g.clemson.edu",
"mcrousseau9@mac.com",
"aspencer8119@gmail.com",
"desvon@gmail.com",
"jlandbrooks@yahoo.com",
"hdowda@yahoo.com",
"sumter1802@yahoo.com",
"bradpetit@gmail.com",
"lagerman64@yahoo.com",
"acleme1709@gmail.com",
"ericr1970@gmail.com",
"shockingbluerose@gmail.com",
"dougpipersr@gmail.com",
"davellowe@gmail.com",
"cosack22@yahoo.com",
"craigoryvol@gmail.com",
"andy@lowtidebrewing.com",
"edwardmarquardt1@gmail.com",
"steel_4501@yahoo.com",
"brian@wanderingbardmeadery.com",
"bbrewer04@yahoo.com",
"john.welsch@comcast.net",
"scott.d.laforge@gmail.com",
"murph269@gmail.com",
"pascoejeff@gmail.com",
"michael.pribble@gmail.com",
"kirk.waters15@gmail.com",
"trevorgildea@gmail.com",
"Breakdownproject@aol.com",
"coxbr101@gmail.com",
"davidholaday@gmail.com",
"jim.griggers@gmail.com",
"beorlufu@gmail.com",
"metm_93@yahoo.com",
"BigJohn3957@gmail.com",
"bennettcowan48@gmail.com",
"theweaveman@gmail.com",
"lilhoser@gmail.com",
"criticalovrload@gmail.com",
"gregory.scott.phillips@gmail.com",
"spencer.tielkemeier@ychhops.com",
"joshua.ray.jackson@gmail.com",
"m.clements07@gmail.com",
"Drewhow1@vt.edu",
"marcekja@gmail.com",
"tanguy.philbert@gmail.com",
"nirupowell@gmail.com",
"visger369@gmail.com",
"sapperaviator@yahoo.com",
"andy.hardison@gmail.com",
"celtgirl@bellsouth.net",
"joandstevo@yahoo.com",
"cdgadd@gmail.com",
"thomas_brandeis@hotmail.com",
"marci@hethmon.com",
"phethmon@hethmon.com",
"stjones1@gmail.com",
"Bradshupe@gmail.com",
"hixland@gmail.com",
"apratsunrthd@gmail.com",
"andythedpt@gmail.com",
"ahight@mrmgt.net",
"Joe.flemingkpt@gmail.com",
"TimothyJenkins1988@gmail.com",
"hogworks@charter.net",
"jmag@chartertn.net",
"kaelem43@yahoo.com",
"johndbolt@gmail.com",
"basevol@comcast.net",
"sealred21@gmail.com",
"bones_n_beers@hotmail.com",
"brantleyandy1@gmail.com",
"adill.gen@gmail.com",
"history.doyle@gmail.com",
"taraynryan@gmail.com",
"herrig@goldmail.etsu.edu",
"tom.hohaus@thecasualpint.com",
"torimccammon@gmail.com",
"johnnypm41@gmail.com",
"beneluximports@gmail.com",
"mpryfogle@gmail.com",
"naillulu@gmail.com",
"tony@tonyteachesbeer.com",
"geojon4609@aol.com",
"alex.shirey@clinchriverbrewing.com",
"rob@knoxbeersnobs.com",
"joncsim2@gmail.com",
"jordaskeen@gmail.com",
"micah.sweeney@gmail.com",
"george.suttrees@gmail.com",
"marty4brew@comcast.net",
"alexjviolette@gmail.com",
"j.m.wesolowski@gmail.com",
"twilso37@vols.utk.edu",
"geraldawitt@gmail.com",
"yust@comcast.net",
"cristianasierra@gmail.com",
"ande4836@gmail.com",
"disney7@gmail.com",
"joe.edidin@gmail.com",
"ryantaylorallen@yahoo.com",
"rrbosio@gmail.com",
"evan.comeaux@gmail.com",
"ryan.e.gauvin@gmail.com",
"will@crosstownbeer.com",
"rjheath@gmail.com",
"eric.hosman@gmail.com",
"midsouthmalts@bellsouth.net",
"cortkiese@gmail.com",
"jmrybak@gmail.com",
"nshort91@gmail.com",
"amsteele81@gmail.com",
"bigmattraby@gmail.com",
"Mrkevinjones@comcast.net",
"johnd0809@hotmail.com",
"aboldham@gmail.com",
"jwingnutt73@gmail.com",
"kencarman@earthlink.net",
"MillieCarman@earthlink.net",
"markforrester@comcast.net",
"sjohnson3@comcast.net",
"krjoseph@gmail.com",
"john.p.lawless.ii@gmail.com",
"tselbrade@gmail.com",
"shwineka@gmail.com",
"john.peed@elotouch.com",
"balahbender@gmail.com",
"joe@joedumas.com",
"tony@barleymob.com",
"veristic7@gmail.com",
"mebedave@netzero.net",
"sommersb@gmail.com",
"dan.tatarka2012@gmail.com",
"tamara.hatley@gmail.com",
"alexanderxespinoza@gmail.com",
"nfhbeer@gmail.com",
"charlie@charleswharr.com",
"jlkasper@gmail.com",
"donacake@comcast.net",
"dnwlee@comcast.net",
"maddbrewer@madfoxbrewing.com",
"j.malmgren@cjmisp.com",
"dennispetersen@yahoo.com",
"kathleenkoch@verizon.net",
"jzorn25@gmail.com",
"braunmm@gmail.com",
"dfc2013@gmail.com",
"marlerbrews@gmail.com",
"jmcadams@gmail.com",
"jaymantn@comcast.net",
"ashore13@vt.edu",
"robertf.silver@gmail.com",
"wendell.a.spencer@gmail.com",
"steveausband@yahoo.com",
"ericallanwest@gmail.com",
"abkulp@gmail.com",
"davidt7826@aol.com",
"hogenmiller@yahoo.com",
"wildchild75@gmail.com",
"jtdarden@gmail.com",
"a.slatosky@gmail.com",
"arminzijerdi@gmail.com",
"matt.white1121@gmail.com",
"c.giacofei@gmail.com",
"jesse.newcomer@gmail.com",
"jchanley@nycap.rr.com",
"maxmurphy12345@gmail.com",
"bjcp@stilltrying.net",
"Jeannelb1@yahoo.com",
"mdonovan17@gmail.com",
"caflem@gmail.com",
"Bobkingdc@verizon.net",
"uminocha@gmail.com",
"kknott@vt.edu",
"PGNewby@yahoo.com",
"chuckarnold03@gmail.com",
"sketerbuck@yahoo.com",
"matt@brewersassociation.org",
"ryann.brzoska@gmail.com",
"bull.thomas@gmail.com",
"fondren@cox.net",
"beergeekjoey@cox.net",
"angela48067@yahoo.com",
"pilgrimhd@gmail.com",
"15meudisbo@gmail.com",
"larsccw@hotmail.com",
"wsoublo@gmail.com",
"stevebremer@hotmail.com",
"kinzieb16@gmail.com",
"whaskell@gmail.com",
"rp22182@yahoo.com",
"maria@stgbeer.com",
"brewnorm@gmail.com",
"b.falman@gmail.com",
"g.cecil@verizon.net",
"noglej@nogle.us",
"beerking1@verizon.net",
"jasperakerboom@gmail.com",
"tony.ponce.va@outlook.com",
"aaron.garnier@gmail.com",
"cdcbjcp@gmail.com",
"hcpainter@gmail.com",
"mihalybaci@gmail.com",
"ericjp72@yahoo.com",
"john@lennerton.com",
"william.spiesberger@gmail.com",
"brewit@jedflight.com",
"tjherrcpa@comcast.net",
"jh.hewit@icloud.com",
"rick@ecologiccleansers.com",
"brian.bergquist99@gmail.com",
"johnpope999@gmail.com",
"bdkelly78@gmail.com",
"jdflamm@mac.com",
"smithj88@aol.com",
"patrickctaylor@rocketmail.com",
"brucetbennett@verizon.net",
"diane.cat@verizon.net",
"tartz@cox.net",
"ken@kenrygh.com",
"aracnid@gmail.com",
"brrengh@gmail.com",
"tyler_kidd@yahoo.com",
"ericscottmckay@gmail.com",
"danmouer@fastmail.fm",
"taphouse.sean@gmail.com",
"bolsoe@gmail.com",
"tcpadden@gmail.com",
"chadrva@gmail.com",
"solsticeshore@gmail.com",
"4eshore@gmail.com",
"mattchusnow07@gmail.com",
"pauldteller@gmail.com",
"dsunc@me.com",
"matthew.klumpp@gmail.com",
"pmmaho@yahoo.com",
"darin-pearson@cox.net",
"bsummerson12@gmail.com",
"kevincampbell27@gmail.com",
"taku_74@yahoo.com",
"bigredhophead@verizon.net",
"waschmidt@cox.net",
"JPSyms@aol.com",
"bdingus@gmail.com",
"dmdefilippis@gmail.com",
"domps02@gmail.com",
"jlmitchell@protonmail.com",
"shyzaboy@yahoo.com",
"tgerbrachtbjcp@gmail.com",
"mark-jackson@verizon.net",
"stjerome03@gmail.com",
"rgpidgeon@verizon.net",
"odell.alex@gmail.com",
"rridgell@vt.edu",
"gohoos85acc@icloud.com",
"bryan.flaherty@yahoo.com",
"immortalco2@gmail.com",
"hayworthdc@gmail.com",
"growlerphil@gmail.com",
"steinsato@hotmail.com",
"dandeibler@gmail.com",
"vajardin@gmail.com"
]

print(len(bjcp))

updated = []

for j in bjcp:
    if j not in ncbc:
        updated.append(j)


print(len(updated))

print()

print(',\n'.join(updated))